# Generated by Django 5.0 on 2023-12-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("notify_at", models.JSONField()),
                ("colour", models.CharField(max_length=7)),
                ("notification_custom_message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EventRepeaterFactory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repeat_every_n_days", models.IntegerField()),
                ("lead_time", models.IntegerField()),
                (
                    "base_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
